version: '2.1'
services:
 # PHP 7.0 FPM
 dev-fpm70:
  container_name: dev-fpm70
  image: envdev/php-fpm:7.0-debian
  volumes:
   - /path/to/workspace:/home/vhosts
  links:
   - "dev-db:db"
   - "dev-redis:redis"
   - "dev-mailcatcher:mailcatcher"
  logging:
   driver: "json-file"
   options:
    max-size: "1g"
    max-file: "10"
  environment:
   LOCAL_USER_ID: 1000
 # MailCatcher
 dev-mailcatcher:
  container_name: dev-mailcatcher
  image: envdev/mailcatcher:0.6.5
  logging:
   driver: "json-file"
   options:
    max-size: "1g"
    max-file: "10"
 # MailCatcher
 dev-redis:
  container_name: dev-redis
  image: envdev/redis:4.0
  logging:
   driver: "json-file"
   options:
    max-size: "1g"
    max-file: "10"
 # MariaDB
 dev-db:
  container_name: dev-db
  image: envdev/mariadb:10.2-debian
  user: mysql
  volumes:
   - /path/to/workspace/database:/var/lib/mysql
  logging:
   driver: "json-file"
   options:
    max-size: "500m"
    max-file: "9"
  environment:
   MARIADB_PASS: password
 # Apache HTTPd
 dev-httpd:
  container_name: dev-httpd
  image: envdev/httpd:2.4-debian
  volumes:
   - /path/to/workspace:/home/vhosts
  links:
   - "dev-fpm70:fpm70"
  logging:
   driver: "json-file"
   options:
    max-size: "1g"
    max-file: "10"
  networks:
   default:
   front:
    ipv4_address: 172.10.0.2

networks:
 front:
  driver: bridge
  ipam:
   driver: default
   config:
    - subnet: 172.10.0.0/16
      gateway: 172.10.0.1
